name: GiphyGIF
include:
  - .swiftlint.yml
  - path: .swiftlint.yml
    relativePaths: false
options:
  bundleIdPrefix: "com.uwaisalqadri"
  deploymentTarget:
    iOS: 16.0
  postGenCommand: xcodebuild -resolvePackageDependencies
  indentWidth: 2
  tabWidth: 2
packages:
  SDWebImageSwiftUI:
    github: SDWebImage/SDWebImageSwiftUI
    version: 2.0.0
  Swinject:
    github: Swinject/Swinject
    version: 2.8.0
  Lottie:
    github: airbnb/lottie-spm
    version: 4.3.0
  Common:
    path: Modules/Common/Common
  Giphy:
    path: Modules/Giphy/Giphy
targets:
  GiphyGIF:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    scheme:
      testTargets:
        - GiphyGIFTests
      gatherCoverageData: true
    dependencies:
      - target: GiphyWidget
      - package: Giphy
      - package: Common
      - package: SDWebImageSwiftUI
      - package: Swinject
      - package: Lottie
    sources:
      - path: GiphyGIF
        excludes:
          - "**/*.md" # excludes all files with the .md extension
    settings:
      base:
        API_KEY: EEx8BY3HX9JrYdFZ4Hdcx4Trbj35k5Ic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: 1.0.0
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: ""
        ENABLE_BITCODE: false
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
          - "$(PROJECT_DIR)/GiphyGIF"
    postCompileScripts:
      - script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi

  GiphyWidget:
    type: app-extension
    subtype: widgetkit-extension
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.uwaisalqadri.GiphyGIF.GiphyWidget
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: GiphyWidget/Info.plist
    sources:
      - path: GiphyWidget
    dependencies:
      - package: Giphy
      - package: Common
      - package: SDWebImageSwiftUI
      - package: Swinject
      - package: Lottie
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
  GiphyGIFTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    dependencies:
      - target: GiphyGIF
    settings:
      CODE_SIGN_STYLE: Automatic
      INFOPLIST_FILE: GiphyGIFTests/Info.plist
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/GiphyGIF.app/GiphyGIF
    scheme:
      testTargets:
        - GiphyGIFTests
    sources:
      - path: GiphyGIFTests
